### ISSUE TITLE
node implementation not working

### ISSUE THREAD

**Issue by bobrundle** [stripe-samples/accept-a-card-payment#10]
The node implementation in the without hooks code set is not working.

To get it working the following needs to be added near the top of server.js

    var bodyParser = require('body-parser');
    app.use(bodyParser.json());

**Comment by mshafrir-stripe** [comment]
@bobrundle thanks for flagging!

**Comment by adreyfus-stripe** [comment]
@bobrundle We're using express's built in middleware so it should already work with this line:

```
app.use(express.json());
``` 

However, that line was missing before I merged [this commit](https://github.com/stripe-samples/accept-a-card-payment/commit/ced1374a33c963d482ea88f29a1ff89a390831f7) a couple days ago so depending on when you pulled it may have been missing! Closing this issue for now but let me know if that doesn't resolve it. Thanks for reporting
