### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by Lecraver** [stripe-samples/accept-a-card-payment#22]
Hi,
I have this display bug when I test this sample :
accept-a-card-payment/using-webhooks/server/php/public/

![image](https://user-images.githubusercontent.com/17044641/78717290-aefdbb80-7920-11ea-95af-a8faa8ab2352.png)

I ran this example locally and with firefox 74.0.1
Everything seems to works well except this display.
Can you help me please ? Thank you,

**Comment by adreyfus-stripe** [comment]
Hi @Lecraver, the card element will stretch to fill 100% of its parent element, so I would try adjusting the width on the parent element to make it a bit wider. That should give enough room for the fields.

**Comment by Lecraver** [comment]
Hi, thank you for the quick reply !
