### ISSUE TITLE
description is required to generate payment result

### ISSUE THREAD

**Issue by juhilsomaiya** [stripe-samples/accept-a-card-payment#24]
Hello team. I'm using android sdk and node backend for my application. I'm using the sample provided which is without the webhook call. 

When I enters the card details and submit for payment it throws error like. : 

> As per indian regulation, export transaction requires a description. 

I've attached screenshot.
[https://drive.google.com/open?id=1jSbsVIWsh-TzQWqTIB84m08PG9lzXUEk](url)

**Comment by ctrudeau-stripe** [comment]
Hello @juhilsomaiya, additional information is required for export transactions. There is a guide here [0]. If you change this block [1] to add a description and additional information depending on if it is an export of services or goods. [2]

[0] https://stripe.com/docs/india-exports#export-of-services
[1] https://github.com/stripe-samples/accept-a-card-payment/blob/master/without-webhooks/server/node/server.js#L37
[2] https://stripe.com/docs/india-exports#export-of-services

**Comment by juhilsomaiya** [comment]
@ctrudeau-stripe Hey, hope you're doing great and safe. 
Thank you for your quick replay. Things you suggested worked for my case.
