### ISSUE TITLE
No such payment_method

### ISSUE THREAD

**Issue by Matiyeu** [stripe-samples/accept-a-card-payment#4]
With webhook I get this error
![image](https://user-images.githubusercontent.com/30661420/69907800-8b5bbf00-13dc-11ea-849a-d28802da29cd.png)

**Comment by adreyfus-stripe** [comment]
@Matiyeu can you provide more details on what you're trying to do? Make sure you are using publishable and secret API keys from the same Stripe account

**Comment by Matiyeu** [comment]
@adreyfus-stripe Yes I follow the README. And yes I fill my .env file with my public & secret key
I use version api :  ``2019-11-05``
 I try only in test mode

**Comment by adreyfus-stripe** [comment]
@Matiyeu The only time I've seen this error is when you are using a publishable key from one Stripe account and a secret key from a different account. If you are still running into this error can you tell me 1) which server language 2) which client (web, ios, android) 3) if you installed it using the Stripe CLI (using the command stripe samples create accept-a-card-payment). Thank you!

**Comment by Matiyeu** [comment]
@adreyfus-stripe Effectivel, the mistake came from my private key that had been badly copied.. Thx

**Comment by adreyfus-stripe** [comment]
@Matiyeu No worries, thanks for following up. Your issue could help someone else one day!
