### ISSUE TITLE
iOS object-C target run error

### ISSUE THREAD

**Issue by zhuleiRedTea** [stripe-samples/accept-a-card-payment#41]
# Bug report
iOS object-C target run error
## Describe the bug
When I download the project from github, it reports an error directly after running pod install, because it is cocoapods installation that I can’t change the code, please tell me how to solve this problem

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'Stripe Example App '
2. Click on 'Stripe Example App object target'
3. run target

## Screenshots
![image](https://user-images.githubusercontent.com/59433421/90851328-ee481880-e3a6-11ea-86f6-11aedb4418b4.png)

## System information

- OS:macOS10.15.6 [e.g. macOS, Windows]

**Comment by yuki-stripe** [comment]
Hi @zhuleiRedTea,

Thanks for the report! You can fix this locally by running `pod update` or pulling the latest master.
