### ISSUE TITLE
go file

### ISSUE THREAD

**Issue by Jsn2win** [stripe-samples/accept-a-card-payment#49]
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Server environment [e.g. Go, Java, Node, PHP, Python, Ruby, TypeScript]

**Comment by cjavilla-stripe** [comment]
Hey @Jsn2win can you say more? It's unclear what the bug is.
