### ISSUE TITLE
Android gson.fromjson() expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by WANG-MengJiao** [stripe-samples/accept-a-card-payment#5]
Hi, there, I am using the android as client and php as server. 
The php = 7.2, stripe/stripe-php = 7.0.
The response json is generated by the following php code sample. 
`$output = [
	'publishableKey' => $config['stripe_publishable_key'],
	'clientSecret' => $paymentIntent->client_secret,
];
echo json_encode($output);`
When I pass the json string from server side to the gson.fromjson() at client side, it outputs the error 'expected BEGIN_OBJECT but was STRING at line 1 column 1 path $'.
What I found is that a 'POST' keyword is added at the beginning of json string, which caused the parsing failure of gson. The gson seems to expect something like {\json_content\}. But now it gets POST{\json_content\}. 
I am confused about the reason why the 'POST' is added. Is there any way to solve this problem?

**Comment by yuki-stripe** [comment]
Hi @WANG-MengJiao, thanks for the report.  

Unfortunately, for our php sample code, you will need to modify the client to use the `create-payment-intent.php` endpoint instead of `create-payment-intent`.  I'm not familiar enough with php to know how to get around this (would love suggestions).
