### ISSUE TITLE
How can I delete postal code from input?

### ISSUE THREAD

**Issue by kmpartner** [stripe-samples/accept-a-card-payment#57]
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Server environment [e.g. Go, Java, Node, PHP, Python, Ruby, TypeScript]

**Comment by cjavilla-stripe** [comment]
Hey @kmpartner yes you can disable the postal code when creating the Card element using the hidePostalCode argument [1].

You'd need to update this line [2] to be the following:

```js
var card = elements.create("card", { style: style, hidePostalCode: true });
```

Hope that helps. Please reach out to support.stripe.com/contact or the engineers on IRC if you run into any problems or have any further questions.


[1] https://stripe.com/docs/js/elements_object/create_element?type=card#elements_create-options-hidePostalCode 
[2] https://github.com/stripe-samples/accept-a-card-payment/blob/master/using-webhooks/client/web/script.js#L57
