### ISSUE TITLE
Error: You need to provide a description for export transactions

### ISSUE THREAD

**Issue by dhavalkasavala** [stripe-samples/accept-a-card-payment#6]
"message": "You need to provide a description for export transactions.",
 "type": "invalid_request_error"
stripe-php version : 6.31

**Comment by dhavalkasavala** [comment]
Resolved this issue you have to pass description param value, in document it is optional value.

**Comment by TheRealTechWiz** [comment]
I followed the instructions given in https://github.com/stripe-samples/accept-a-card-payment/blob/master/README.md and I am getting the same error. How can I add description and solve this issue.
