### ISSUE TITLE
Stripe

### ISSUE THREAD

**Issue by Madow92** [stripe-samples/accept-a-card-payment#62]
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Server environment [e.g. Go, Java, Node, PHP, Python, Ruby, TypeScript]

**Comment by cjavilla-stripe** [comment]
Hey there. I don't see any context. Can you share more about what you're seeing?

**Comment by Madow92** [comment]
I probably happened to access the wrong button! 🙈

**Comment by cjavilla-stripe** [comment]
No worries. Thanks for following up :) Cheers!
