### ISSUE TITLE
Please help me for stripe integration in angular 7

### ISSUE THREAD

**Issue by shoaib0906** [stripe-samples/accept-a-card-payment#68]
I can't push amount value for payment to stripe in my angular js project.

Code is below here::

<button (click)="pay('{{milestone.milestone_value}}')" class="btn btn-primary btn-block">Pay {{milestone.milestone_value | currency: '$' }}</button>

Please help me to set the amount into "pay(???)"

Thanks in advance.

**Comment by cjavilla-stripe** [comment]
Hey @shoaib0906.

Can you add a bit more context? I'm not sure what you mean by pushing the amount value. In this sample, the amount is defined on the server when creating the PaymentIntent. Passing the amount from the client is discouraged unless you're building a donation site as users could modify the amount on the client before it hits the server.

For faster support, I recommend reaching out to support.stripe.com/contact. In case it's helpful, there are Stripe engineers available to chat during most business hours in the #stripe channel on Freenode (https://webchat.freenode.net/?channel=#stripe).
