### ISSUE TITLE
Excuse me, I want to ask a question, when I know the bank card information, can I automatically fill in the input box?

### ISSUE THREAD

**Issue by xiaozhou-amazing** [stripe-samples/accept-a-card-payment#75]
Excuse me, I want to ask a question, when I know the bank card information, can I automatically fill in the input box?

**Comment by paulasjes-stripe** [comment]
Hi there, programmatically filling in card details into Elements is not possible as the inputs are hosted within an iframe on a Stripe domain. This is intentionally done for security reasons, it also protects you by making your integration [PCI compliant](https://stripe.com/docs/security/guide#validating-pci-compliance). 

Passing raw card numbers directly to the Stripe API is heavily discouraged as it means you have to be fully PCI compliant and be completely responsible for the security of those card numbers. 

If this is still an integration path you wish you explore I recommend reaching out to Stripe support directly: https://support.stripe.com/contact
